name: main-terraform

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/873779737071/locations/global/workloadIdentityPools/actions-pool/providers/actions-provider'
          service_account: 'terraform@terraform-391612.iam.gserviceaccount.com'
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -input=false
      
      - name: Terraform Branch Workspace
        run: terraform workspace new $GITHUB_HEAD_REF
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
      
      - name: Terraform Format
        run: terraform fmt -check -recursive -diff

      - name: Terraform Validate
        run: terraform validate
      
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan -var-file=terraform.tfvars
      
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
        
      - name: Terraform Cleanup
        if: always()
        run: |
          terraform destroy -input=false -auto-approve -var-file=terraform.tfvars || exit 1
          terraform workspace select default
          terraform workspace delete $GITHUB_HEAD_REF
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}